# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "nice_nano" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano
#     shield: reviung41
#   - board: nice_nano
#     shield: corne_left
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: corne_left_with_studio
#
---
include:
  # Dongle Setup
  - board: nice_nano
    shield: sofle_dongle
    artifact-name: sofle_dongle
  - board: nice_nano@2.0.0
    shield: sofle_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: sofle_left_dongle
  - board: nice_nano@2.0.0
    shield: sofle_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: sofle_right_dongle

  # Standard Setup (Direct BLE)
  - board: nice_nano@2.0.0
    shield: sofle_left
    artifact-name: sofle_left_standard
  - board: nice_nano@2.0.0
    shield: sofle_right
    artifact-name: sofle_right_standard

  - board: nice_nano
    shield: settings_reset
